### ISSUE TITLE
apollo系统错误请重试或联系系统管理员

### ISSUE THREAD

**Issue by YixiaoOneSmile** [zengqinglei/microservice-deploy#1]
作者您好，读了您的文章受益匪浅，有一些问题能否进行交流？

**Comment by zengqinglei** [comment]
Hi:
看了你给我发的邮件，你需要配置途中这个位置：
![image](https://user-images.githubusercontent.com/7374317/71567035-212b5c80-2af7-11ea-950d-abc2d0f1ace0.png)
这里可以指定不同环境的服务中心的地址
